# Observium and MariaDB container
# Created by somsakc@hotmail.com
# Maintained by roccas@gmail.com

version: '3'

services:
  observiumdb:
       build: .
       environment:
         - MYSQL_ROOT_PASSWORD=passw0rd
         - MYSQL_USER=observium
         - MYSQL_PASSWORD=passw0rd
         - MYSQL_DATABASE=observium
         - OBSERVIUM_ADMIN_USER=admin
         - OBSERVIUM_ADMIN_PASS=passw0rd
         - OBSERVIUM_DB_HOST=observiumdb
         - OBSERVIUM_DB_NAME=observium
         - OBSERVIUM_DB_USER=observium 
         - OBSERVIUM_DB_PASS=passw0rd
         - OBSERVIUM_BASE_URL=http://10.55.5.92:8668
         - TZ=America/Argentina/Mendoza
       volumes:
         - /opt/observium/mysql:/var/lib/mysql
#         - /opt/observium/mysql:/docker-entrypoint-initdb.d
         - /opt/observium/logs:/opt/observium/logs
         - /opt/observium/lock:/opt/observium/lock
         - /opt/observium/rrd:/opt/observium/rrd
       ports:
         - "8668:80"
       restart: always
